import { IPlayerModel } from "../models/player-model";

export const playerDatabase: IPlayerModel[] = [
  {
    id: 1,
    name: "Lionel Messi",
    club: "Inter Miami",
    nationality: "Argentina",
    position: "RW",
    statistics: {
      overall: 93,
      pace: 85,
      shooting: 92,
      passing: 91,
      dribbling: 95,
      defending: 38,
      physicality: 65,
    },
  },
  {
    id: 2,
    name: "Cristiano Ronaldo",
    club: "Al Nassr",
    nationality: "Portugal",
    position: "ST",
    statistics: {
      overall: 91,
      pace: 87,
      shooting: 93,
      passing: 82,
      dribbling: 88,
      defending: 35,
      physicality: 77,
    },
  },
  {
    id: 3,
    name: "Kylian Mbappé",
    club: "Paris Saint-Germain",
    nationality: "France",
    position: "ST",
    statistics: {
      overall: 92,
      pace: 97,
      shooting: 89,
      passing: 80,
      dribbling: 92,
      defending: 36,
      physicality: 78,
    },
  },
  {
    id: 4,
    name: "Kevin De Bruyne",
    club: "Manchester City",
    nationality: "Belgium",
    position: "CM",
    statistics: {
      overall: 91,
      pace: 76,
      shooting: 86,
      passing: 94,
      dribbling: 88,
      defending: 64,
      physicality: 78,
    },
  },
  {
    id: 5,
    name: "Virgil van Dijk",
    club: "Liverpool",
    nationality: "Netherlands",
    position: "CB",
    statistics: {
      overall: 90,
      pace: 78,
      shooting: 60,
      passing: 71,
      dribbling: 72,
      defending: 92,
      physicality: 86,
    },
  },
  {
    id: 6,
    name: "Neymar Jr.",
    club: "Al Hilal",
    nationality: "Brazil",
    position: "LW",
    statistics: {
      overall: 91,
      pace: 91,
      shooting: 85,
      passing: 84,
      dribbling: 94,
      defending: 36,
      physicality: 59,
    },
  },
  {
    id: 7,
    name: "Robert Lewandowski",
    club: "Barcelona",
    nationality: "Poland",
    position: "ST",
    statistics: {
      overall: 91,
      pace: 78,
      shooting: 92,
      passing: 79,
      dribbling: 86,
      defending: 43,
      physicality: 84,
    },
  },
  {
    id: 8,
    name: "Mohamed Salah",
    club: "Liverpool",
    nationality: "Egypt",
    position: "RW",
    statistics: {
      overall: 90,
      pace: 89,
      shooting: 87,
      passing: 81,
      dribbling: 90,
      defending: 45,
      physicality: 75,
    },
  },
  {
    id: 9,
    name: "Karim Benzema",
    club: "Al-Ittihad",
    nationality: "France",
    position: "ST",
    statistics: {
      overall: 89,
      pace: 75,
      shooting: 90,
      passing: 84,
      dribbling: 87,
      defending: 41,
      physicality: 77,
    },
  },
  {
    id: 10,
    name: "Luka Modrić",
    club: "Real Madrid",
    nationality: "Croatia",
    position: "CM",
    statistics: {
      overall: 88,
      pace: 72,
      shooting: 80,
      passing: 91,
      dribbling: 90,
      defending: 72,
      physicality: 65,
    },
  },
  {
    id: 11,
    name: "Sadio Mané",
    club: "Al Nassr",
    nationality: "Senegal",
    position: "LW",
    statistics: {
      overall: 88,
      pace: 92,
      shooting: 83,
      passing: 80,
      dribbling: 90,
      defending: 46,
      physicality: 76,
    },
  },
  {
    id: 12,
    name: "Erling Haaland",
    club: "Manchester City",
    nationality: "Norway",
    position: "ST",
    statistics: {
      overall: 89,
      pace: 88,
      shooting: 89,
      passing: 75,
      dribbling: 80,
      defending: 45,
      physicality: 92,
    },
  },
  {
    id: 13,
    name: "Harry Kane",
    club: "Bayern Munich",
    nationality: "England",
    position: "ST",
    statistics: {
      overall: 89,
      pace: 77,
      shooting: 89,
      passing: 79,
      dribbling: 82,
      defending: 44,
      physicality: 86,
    },
  },
  {
    id: 14,
    name: "Thibaut Courtois",
    club: "Real Madrid",
    nationality: "Belgium",
    position: "GK",
    statistics: {
      overall: 90,
      pace: 50,
      shooting: 30,
      passing: 58,
      dribbling: 29,
      defending: 90,
      physicality: 86,
    },
  },
  {
    id: 15,
    name: "Jan Oblak",
    club: "Atletico Madrid",
    nationality: "Slovenia",
    position: "GK",
    statistics: {
      overall: 91,
      pace: 54,
      shooting: 25,
      passing: 57,
      dribbling: 29,
      defending: 89,
      physicality: 88,
    },
  },
  {
    id: 16,
    name: "Alisson Becker",
    club: "Liverpool",
    nationality: "Brazil",
    position: "GK",
    statistics: {
      overall: 90,
      pace: 53,
      shooting: 30,
      passing: 60,
      dribbling: 28,
      defending: 90,
      physicality: 88,
    },
  },
  {
    id: 17,
    name: "Joshua Kimmich",
    club: "Bayern Munich",
    nationality: "Germany",
    position: "CDM",
    statistics: {
      overall: 90,
      pace: 79,
      shooting: 77,
      passing: 89,
      dribbling: 83,
      defending: 90,
      physicality: 82,
    },
  },
  {
    id: 18,
    name: "N'Golo Kanté",
    club: "Al-Ittihad",
    nationality: "France",
    position: "CDM",
    statistics: {
      overall: 89,
      pace: 80,
      shooting: 66,
      passing: 82,
      dribbling: 85,
      defending: 91,
      physicality: 79,
    },
  },
  {
    id: 19,
    name: "Sergio Ramos",
    club: "Sevilla",
    nationality: "Spain",
    position: "CB",
    statistics: {
      overall: 87,
      pace: 70,
      shooting: 66,
      passing: 75,
      dribbling: 74,
      defending: 89,
      physicality: 86,
    },
  },
  {
    id: 20,
    name: "Raphaël Varane",
    club: "Manchester United",
    nationality: "France",
    position: "CB",
    statistics: {
      overall: 86,
      pace: 82,
      shooting: 55,
      passing: 74,
      dribbling: 72,
      defending: 88,
      physicality: 84,
    },
  },
  {
    id: 21,
    name: "Trent Alexander-Arnold",
    club: "Liverpool",
    nationality: "England",
    position: "RB",
    statistics: {
      overall: 87,
      pace: 75,
      shooting: 78,
      passing: 90,
      dribbling: 83,
      defending: 80,
      physicality: 70,
    },
  },
  {
    id: 22,
    name: "Andrew Robertson",
    club: "Liverpool",
    nationality: "Scotland",
    position: "LB",
    statistics: {
      overall: 86,
      pace: 78,
      shooting: 68,
      passing: 87,
      dribbling: 80,
      defending: 85,
      physicality: 75,
    },
  },
  {
    id: 23,
    name: "Frenkie de Jong",
    club: "Barcelona",
    nationality: "Netherlands",
    position: "CM",
    statistics: {
      overall: 89,
      pace: 75,
      shooting: 77,
      passing: 90,
      dribbling: 88,
      defending: 84,
      physicality: 80,
    },
  },
  {
    id: 24,
    name: "Bruno Fernandes",
    club: "Manchester United",
    nationality: "Portugal",
    position: "CAM",
    statistics: {
      overall: 88,
      pace: 75,
      shooting: 85,
      passing: 89,
      dribbling: 88,
      defending: 65,
      physicality: 78,
    },
  },
  {
    id: 25,
    name: "Paul Pogba",
    club: "Juventus",
    nationality: "France",
    position: "CM",
    statistics: {
      overall: 85,
      pace: 75,
      shooting: 84,
      passing: 84,
      dribbling: 87,
      defending: 77,
      physicality: 86,
    },
  },
  {
    id: 26,
    name: "Toni Kroos",
    club: "Real Madrid",
    nationality: "Germany",
    position: "CM",
    statistics: {
      overall: 89,
      pace: 68,
      shooting: 84,
      passing: 92,
      dribbling: 86,
      defending: 75,
      physicality: 74,
    },
  },
  {
    id: 27,
    name: "Lautaro Martínez",
    club: "Inter Milan",
    nationality: "Argentina",
    position: "ST",
    statistics: {
      overall: 86,
      pace: 84,
      shooting: 84,
      passing: 80,
      dribbling: 85,
      defending: 40,
      physicality: 82,
    },
  },
  {
    id: 28,
    name: "Heung-Min Son",
    club: "Tottenham",
    nationality: "South Korea",
    position: "LW",
    statistics: {
      overall: 87,
      pace: 85,
      shooting: 85,
      passing: 81,
      dribbling: 86,
      defending: 45,
      physicality: 78,
    },
  },
  {
    id: 29,
    name: "Marco Verratti",
    club: "Paris Saint-Germain",
    nationality: "Italy",
    position: "CM",
    statistics: {
      overall: 87,
      pace: 75,
      shooting: 73,
      passing: 91,
      dribbling: 85,
      defending: 80,
      physicality: 69,
    },
  },
  {
    id: 30,
    name: "Eden Hazard",
    club: "Grealish FC",
    nationality: "Belgium",
    position: "LM",
    statistics: {
      overall: 85,
      pace: 82,
      shooting: 83,
      passing: 85,
      dribbling: 88,
      defending: 50,
      physicality: 60,
    },
  },
  {
    id: 31,
    name: "Romelu Lukaku",
    club: "AS Roma",
    nationality: "Belgium",
    position: "ST",
    statistics: {
      overall: 86,
      pace: 78,
      shooting: 87,
      passing: 75,
      dribbling: 79,
      defending: 44,
      physicality: 88,
    },
  },
  {
    id: 32,
    name: "Raheem Sterling",
    club: "Chelsea",
    nationality: "England",
    position: "LW",
    statistics: {
      overall: 87,
      pace: 92,
      shooting: 83,
      passing: 84,
      dribbling: 89,
      defending: 48,
      physicality: 68,
    },
  },
  {
    id: 33,
    name: "Jadon Sancho",
    club: "Manchester United",
    nationality: "England",
    position: "RW",
    statistics: {
      overall: 86,
      pace: 88,
      shooting: 83,
      passing: 85,
      dribbling: 87,
      defending: 50,
      physicality: 70,
    },
  },
  {
    id: 34,
    name: "Phil Foden",
    club: "Manchester City",
    nationality: "England",
    position: "CAM",
    statistics: {
      overall: 86,
      pace: 82,
      shooting: 84,
      passing: 87,
      dribbling: 88,
      defending: 65,
      physicality: 68,
    },
  },
  {
    id: 35,
    name: "Vinícius Júnior",
    club: "Real Madrid",
    nationality: "Brazil",
    position: "LW",
    statistics: {
      overall: 86,
      pace: 95,
      shooting: 80,
      passing: 78,
      dribbling: 93,
      defending: 37,
      physicality: 57,
    },
  },
  {
    id: 36,
    name: "Pedri",
    club: "Barcelona",
    nationality: "Spain",
    position: "CM",
    statistics: {
      overall: 85,
      pace: 82,
      shooting: 79,
      passing: 87,
      dribbling: 88,
      defending: 72,
      physicality: 60,
    },
  },
  {
    id: 37,
    name: "Jorginho",
    club: "Arsenal",
    nationality: "Italy",
    position: "CDM",
    statistics: {
      overall: 84,
      pace: 64,
      shooting: 75,
      passing: 89,
      dribbling: 82,
      defending: 83,
      physicality: 70,
    },
  },
  {
    id: 38,
    name: "Kai Havertz",
    club: "Chelsea",
    nationality: "Germany",
    position: "CAM",
    statistics: {
      overall: 85,
      pace: 75,
      shooting: 83,
      passing: 84,
      dribbling: 84,
      defending: 70,
      physicality: 77,
    },
  },
  {
    id: 39,
    name: "Achraf Hakimi",
    club: "Paris Saint-Germain",
    nationality: "Morocco",
    position: "RB",
    statistics: {
      overall: 87,
      pace: 94,
      shooting: 75,
      passing: 83,
      dribbling: 87,
      defending: 78,
      physicality: 76,
    },
  },
  {
    id: 40,
    name: "Wout Weghorst",
    club: "Atlanta Utd",
    nationality: "Netherlands",
    position: "ST",
    statistics: {
      overall: 83,
      pace: 63,
      shooting: 82,
      passing: 72,
      dribbling: 71,
      defending: 47,
      physicality: 90,
    },
  },
  {
    id: 41,
    name: "Ciro Immobile",
    club: "Lazio",
    nationality: "Italy",
    position: "ST",
    statistics: {
      overall: 84,
      pace: 82,
      shooting: 82,
      passing: 72,
      dribbling: 76,
      defending: 40,
      physicality: 80,
    },
  },
  {
    id: 42,
    name: "Gianluigi Donnarumma",
    club: "PSG",
    nationality: "Italy",
    position: "GK",
    statistics: {
      overall: 85,
      pace: 58,
      shooting: 30,
      passing: 60,
      dribbling: 28,
      defending: 87,
      physicality: 85,
    },
  },
  {
    id: 43,
    name: "Marc-André ter Stegen",
    club: "Barcelona",
    nationality: "Germany",
    position: "GK",
    statistics: {
      overall: 90,
      pace: 55,
      shooting: 28,
      passing: 65,
      dribbling: 25,
      defending: 89,
      physicality: 82,
    },
  },
  {
    id: 44,
    name: "Leon Goretzka",
    club: "Bayern Munich",
    nationality: "Germany",
    position: "CM",
    statistics: {
      overall: 86,
      pace: 77,
      shooting: 80,
      passing: 81,
      dribbling: 82,
      defending: 85,
      physicality: 90,
    },
  },
  {
    id: 45,
    name: "Gerard Piqué",
    club: "Retired",
    nationality: "Spain",
    position: "CB",
    statistics: {
      overall: 83,
      pace: 65,
      shooting: 42,
      passing: 78,
      dribbling: 70,
      defending: 85,
      physicality: 85,
    },
  },
  {
    id: 46,
    name: "Jules Koundé",
    club: "Barcelona",
    nationality: "France",
    position: "CB",
    statistics: {
      overall: 85,
      pace: 85,
      shooting: 60,
      passing: 78,
      dribbling: 82,
      defending: 85,
      physicality: 78,
    },
  },
  {
    id: 47,
    name: "Milan Škriniar",
    club: "PSG",
    nationality: "Slovakia",
    position: "CB",
    statistics: {
      overall: 85,
      pace: 72,
      shooting: 58,
      passing: 75,
      dribbling: 74,
      defending: 87,
      physicality: 85,
    },
  },
  {
    id: 48,
    name: "Kyle Walker",
    club: "Manchester City",
    nationality: "England",
    position: "RB",
    statistics: {
      overall: 85,
      pace: 90,
      shooting: 60,
      passing: 78,
      dribbling: 80,
      defending: 83,
      physicality: 85,
    },
  },
  {
    id: 49,
    name: "Reece James",
    club: "Chelsea",
    nationality: "England",
    position: "RB",
    statistics: {
      overall: 85,
      pace: 82,
      shooting: 77,
      passing: 79,
      dribbling: 80,
      defending: 84,
      physicality: 83,
    },
  },
  {
    id: 50,
    name: "Bukayo Saka",
    club: "Arsenal",
    nationality: "England",
    position: "RW",
    statistics: {
      overall: 85,
      pace: 92,
      shooting: 81,
      passing: 83,
      dribbling: 89,
      defending: 45,
      physicality: 70,
    },
  },
];
